## numpy

In [3]:
import numpy as np

## numpy types

In [7]:
n = np.int32(3)
print(n)
print(type(n))

3
<class 'numpy.int32'>


In [8]:
n = np.float64(3)
print(n)
print(type(n))

3.0
<class 'numpy.float64'>


In [16]:
n = np.bool(1)
print(n)
print(type(n))

True
<class 'bool'>


## numpy matrix

In [2]:
A = np.array([[1, 2],[3, 4]])
print(A)

[[1 2]
 [3 4]]


In [3]:
B = 2 * np.identity(2) # broadcast
print(B)

[[2. 0.]
 [0. 2.]]


In [4]:
print(A@B)
print(A*B)

[[2. 4.]
 [6. 8.]]
[[2. 0.]
 [0. 8.]]


In [5]:
print(A[0,0])
print(A[0,:])
print(A[:,0])
print(A[1,1])

1
[1 2]
[1 3]
4


In [6]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## numpy is different from the plain python array

In [7]:
# This isn't for mathematics
print(2 * [1,2])

[1, 2, 1, 2]


In [8]:
# This doesn't work
# print(2 * [1,2] + 1)

In [9]:
# it works with numpy
2 * np.array([1,2]) + 1

array([3, 5])

## Guess how numpy was implemented

In [10]:
class Number:
    def __init__(self, n):
        self.n = n
    def __add__(self, anotherNumber):
        return Number(self.n + anotherNumber.n + 0.01)
    def __str__(self):
        return str(self.n)
    def __repr__(self):
        return str(self)

In [11]:
a = Number(1)
b = Number(2)
c = Number(3)
a + b + c + a + b + c

12.049999999999999