In [1]:
import tensorflow as tf

In [2]:
message = tf.constant('Hello World!')
message

<tf.Tensor: id=0, shape=(), dtype=string, numpy=b'Hello World!'>

In [3]:
a = tf.constant(2)
b = tf.constant(3)
print(a)
print(b)

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)


In [4]:
s = a + b
p = a * b
print(s)
print(p)

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)


In [5]:
s = tf.add(a, b)
p = tf.multiply(a, b)
print(s)
print(p)

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)


In [6]:
mat1 = tf.constant([[3., 3.]])
mat2 = tf.constant([[2.],[2.]])
p = mat1@mat2

print(mat1)
print(mat2)
print(p)

tf.Tensor([[3. 3.]], shape=(1, 2), dtype=float32)
tf.Tensor(
[[2.]
 [2.]], shape=(2, 1), dtype=float32)
tf.Tensor([[12.]], shape=(1, 1), dtype=float32)


In [7]:
# to numpy object
print(mat1.numpy())
print(mat2.numpy())
print(p.numpy())

[[3. 3.]]
[[2.]
 [2.]]
[[12.]]


In [8]:
#SGD
x = tf.Variable(0.0)

optimizer = tf.keras.optimizers.SGD(0.01)

print(0, x)
for i in range(1000):
    def y_func():
        return (x-2)**2
    trainable_variables = [x]
    optimizer.minimize(y_func, var_list=trainable_variables)
    if (i + 1) % 50 == 0:
        print(i + 1, x)

W0729 10:06:40.857129 139714173994816 deprecation.py:323] From /home/hotohoto/playground/py2ml_course/venv/lib/python3.6/site-packages/tensorflow/python/ops/math_grad.py:1205: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


0 <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=0.0>
50 <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.2716603>
100 <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.7347608>
150 <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.9034079>
200 <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.9648241>
250 <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.98719>
300 <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.9953352>
350 <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.9983015>
400 <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.9993814>
450 <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.9997748>
500 <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.999918>
550 <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.9999701>
600 <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.999989>
650 <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.9999961>
700 <tf.Variable 'V

In [9]:
x = tf.Variable(0.0)

optimizer = tf.keras.optimizers.Adam(0.01)

print(0, x)
for i in range(1000):
    def y_func():
        return (x-2)**2
    trainable_variables = [x]
    optimizer.minimize(y_func, var_list=trainable_variables)
    if (i + 1) % 50 == 0:
        print(i + 1, x)

0 <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=0.0>
50 <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=0.4834109>
100 <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=0.9015511>
150 <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.2417164>
200 <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.5035741>
250 <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.6929402>
300 <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.8209624>
350 <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.9017105>
400 <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.9492257>
450 <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.9753326>
500 <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.9887381>
550 <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.9951735>
600 <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.9980612>
650 <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.9992714>
700 <tf.Variabl