In [1]:
import torch

x = torch.Tensor([[1],[5]])
x.requires_grad = True
w = torch.Tensor([[0,1],[1,0]])
v = torch.Tensor([[2]])

y = x.t() @ w @ x

# y = 2 * x1 * x2 // f(x1,x2)
# J = [[2*x2, 2*x1] // [[df/dx1, df/dx2]]
# J^T = [[2 * x2], [ 2 * x1]] // [[df/dx1], [df/dx2]]
# v = [[2]]

print(x)
print(w)
print(y)
print(x.grad)
y.backward(v)
print(x.grad)

tensor([[1.],
        [5.]], requires_grad=True)
tensor([[0., 1.],
        [1., 0.]])
tensor([[10.]], grad_fn=<MmBackward>)
None
tensor([[20.],
        [ 4.]])


In [2]:
import torch

x = torch.Tensor([[1],[5]])
x.requires_grad = True
w = torch.Tensor([[0,1],[1,0]])
v = torch.Tensor([[1]])

y = x.t() @ w @ x

# y = 2 * x1 * x2
# J = [[2*x2, 2*x1]
# J^T = [[2 * x2], [ 2 * x1]]
# v = [[1], [1]]

print(x)
print(w)
print(y)
y.backward()
print(x.grad)

tensor([[1.],
        [5.]], requires_grad=True)
tensor([[0., 1.],
        [1., 0.]])
tensor([[10.]], grad_fn=<MmBackward>)
tensor([[10.],
        [ 2.]])


In [3]:
import torch

x = torch.randn(2, 1, requires_grad=True)
w = torch.Tensor([[1,2], [3,4]])
v = torch.Tensor([[1], [1]])

y = w @ x

# y1 = x1 + 2x2
# y2 = 3x1 + 4x2
# J = [[1,2], [3,4]]
# J^T = [[1,3], [2,4]]
# v = [[1], [1]]

print(x)
print(w)
print(y)
y.backward(v)
print(x.grad)

tensor([[ 0.1518],
        [-0.3446]], requires_grad=True)
tensor([[1., 2.],
        [3., 4.]])
tensor([[-0.5374],
        [-0.9231]], grad_fn=<MmBackward>)
tensor([[4.],
        [6.]])
